name: Our Pyhton app
on: [push]

jobs:
  build:
    name: Autograding Test max flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalar dependencias de Python para el Test
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy scipy networkx

      - name: Ejecutar pytest
        run: pytest test_ff.py
